# Generated by Django 5.2.6 on 2025-11-27 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Milk, Rice, Apples', max_length=100)),
                ('quantity', models.CharField(help_text='Example: 1L, 2kg, 5 pieces', max_length=50)),
                ('category', models.CharField(blank=True, help_text='Optional: Fruits, Dairy, Grains, etc.', max_length=50)),
                ('added_date', models.DateField(auto_now_add=True, help_text='Automatically set when the item is created.')),
                ('expiry_date', models.DateField(help_text='When this item is expected to expire.')),
                ('status', models.CharField(choices=[('FRESH', 'Fresh'), ('EXPIRING', 'Expiring Soon'), ('EXPIRED', 'Expired'), ('DONATED', 'Donated'), ('CONSUMED', 'Consumed')], default='FRESH', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Anything extra: brand, storage place, etc.')),
                ('user', models.ForeignKey(help_text='The owner of this food item.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
