# Generated by Django 5.2.6 on 2025-12-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_fooditem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='status',
            field=models.CharField(choices=[('FRESH', 'Fresh'), ('EXPIRING', 'Expiring Soon'), ('EXPIRED', 'Expired'), ('DONATE', 'Marked for Donation'), ('DONATED', 'Donated'), ('DONATION_CANCELLED', 'Donation Cancelled'), ('CONSUMED', 'Consumed')], default='FRESH', max_length=30),
        ),
    ]
